SELECT ((SYSDATE+.25) - SYSDATE)+SYSDATE FROM DUAL

SELECT 1.5/24 FROM DUAL

SELECT 0.0416666666666667*24 FROM DUAL


SELECT *   FROM EX_PEDIDOS

SELECT * FROM EX_DESCANSOS

INSERT INTO EX_DESCANSOS VALUES (TO_DATE('28/09/2019 12:00:00','DD/MM/YYYY HH24:MI:SS'),TO_DATE('28/09/2019 13:00:00','DD/MM/YYYY HH24:MI:SS'));

//////////////////////

            SELECT COUNT(1)
--            INTO   LN_DESC_EXIS
            FROM   EX_DESCANSOS D
            WHERE  1=1
--            AND    D.INICIO > LD_COLOCADO 
--            AND    D.INICIO < LD_ESTIMADO
            AND    D.INICIO BETWEEN SYSDATE AND SYSDATE+0.0625
            OR     SYSDATE BETWEEN D.INICIO AND D.FIN
            
            