--SELECT * FROM EX_PEDIDOS
--SELECT * FROM EX_DESCANSOS

DROP TABLE EX_PEDIDOS;

CREATE TABLE EX_PEDIDOS
(
NO_PEDIDO      NUMBER,
FECHA_COLOCADO DATE,
HORAS          NUMBER,
ESTATUS        NUMBER,
FECHA_ESTIMADO DATE
);

DROP TABLE EX_DESCANSOS;

CREATE TABLE EX_DESCANSOS
(
INICIO DATE,
FIN    DATE
);